# Generated by Django 5.2.8 on 2025-11-10 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g., 'cats-event' for /cats-event/)", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Event name displayed on the booking page', max_length=255)),
                ('description', models.TextField(help_text='Event description (supports HTML)')),
                ('venue_details', models.TextField(help_text='Venue, date, time information')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, help_text='Base price per ticket (£). Set to 0 for donation-only events.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_donation_based', models.BooleanField(default=False, help_text='If true, shows Gift Aid option (for UK charitable donations)')),
                ('allow_extra_donation', models.BooleanField(default=False, help_text='Allow attendees to add an optional extra donation')),
                ('reference_prefix', models.CharField(default='TKT', help_text="Prefix for booking references (e.g., 'SIB' creates 'SIB-123')", max_length=10)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('sort_code', models.CharField(help_text='Format: 12-34-56', max_length=10)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=20)),
                ('contact_email', models.EmailField(help_text='Contact email shown to customers', max_length=254)),
                ('admin_notification_emails', models.TextField(help_text='Comma-separated list of emails to notify on new bookings')),
                ('confirmation_email_subject', models.CharField(default='Booking Confirmation - {{ event.name }}', max_length=255)),
                ('confirmation_email_body', models.TextField(default='<html><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">\n<h1>Booking Confirmation</h1>\n<p>Dear {{ booking.full_name }},</p>\n<p>Thank you for booking {{ booking.num_tickets }} ticket(s) for {{ event.name }}.</p>\n\n<h2>Your Booking</h2>\n<p><strong>Reference:</strong> {{ booking.booking_reference }}<br>\n<strong>Tickets:</strong> {{ booking.num_tickets }}<br>\n<strong>Total:</strong> £{{ booking.donation_amount }}</p>\n\n<h2>Payment Instructions</h2>\n<p>Please complete payment via bank transfer:</p>\n<ul>\n<li><strong>Account Name:</strong> {{ bank_account_name }}</li>\n<li><strong>Sort Code:</strong> {{ sort_code }}</li>\n<li><strong>Account Number:</strong> {{ account_number }}</li>\n<li><strong>Reference:</strong> {{ payment_reference }}</li>\n<li><strong>Amount:</strong> £{{ booking.donation_amount }}</li>\n</ul>\n<p><strong>Important:</strong> Please include the reference number!</p>\n\n<p>Looking forward to seeing you!<br>\nContact: {{ event.contact_email }}</p>\n</body></html>', help_text='HTML email template. Available variables: {{ booking.* }}, {{ event.* }}, {{ payment_reference }}, {{ bank_* }}')),
                ('is_active', models.BooleanField(default=True, help_text='Only active events accept new bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('num_tickets', models.PositiveIntegerField(default=1)),
                ('donation_amount', models.DecimalField(decimal_places=2, help_text='Total amount (tickets + optional donation)', max_digits=10)),
                ('gift_aid', models.BooleanField(default=False)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.event')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
