# Generated by Django 5.2.8 on 2025-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='collect_phone_number',
            field=models.BooleanField(default=False, help_text='If true, shows phone number field on booking form'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(help_text='Contact email shown to customers (also used as Reply-To address for confirmation emails)', max_length=254),
        ),
    ]
