# Generated by Django 5.2.8 on 2025-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_event_description_event_collect_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quick_pay_link',
            field=models.CharField(blank=True, help_text="Optional quick payment link template (e.g., 'https://monzo.me/tomdyson/{amount}' or 'https://paypal.me/tomdyson/{amount}/GBP'). Use {amount} as placeholder for the payment amount.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_details',
            field=models.TextField(help_text='Venue, date, time information. You can use <strong> or <b> for emphasis.'),
        ),
    ]
